#!/usr/bin/env python3

import sys


def cam2low(cam):
    low = ''
    for ch in cam:
        if 'A' <= ch <= 'Z':
            low += '_'
        low += ch

    return low.lower()


def main():
    for line in sys.stdin:
        print(cam2low(line[:-1]))


if __name__ == '__main__':
    main()
