#!/usr/bin/env python3

import sys


def formater(fmt, word, count):
    return fmt.format(w=word, c=count)


def main():
    count = 0 if len(sys.argv) <= 2 else int(sys.argv[2])
    for line in sys.stdin:
        print(formater(sys.argv[1], line[:-1], count))
        count += 1


if __name__ == '__main__':
    main()
