#!/usr/bin/env bash

function warn() {
    echo "[31m$1[0m"
}

function info() {
    echo "[32m$1[0m"
}

function trac() {
    echo "$1"
}

function install_redis() {
    output=$1
    bin=${output}/bin
    mkdir -p ${output}/bin
    mkdir -p source && cd source &&
    wget http://download.redis.io/releases/redis-3.2.8.tar.gz &&
    tar -xzvf redis-3.2.8.tar.gz &&
    cd redis-3.2.8 &&
    make -j8 &&
    cp src/redis-server ${bin} &&
    cp src/redis-cli ${bin} &&
    cp src/redis-trib.rb ${bin} &&
    cp src/redis-sentinel ${bin} &&
    gem install redis &&
    trac "export PATH=${output}/bin:\$PATH" &&
    info "install redis to $output success." && return 0
    warn "install redis to $output failed." && return 255
}

function install_go() {
    output=$1
    mkdir -p source && cd source &&
    wget https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz &&
    tar -xzvf go1.8.linux-amd64.tar.gz &&
    cp -r go/bin ${output} &&
    cp -r go/lib ${output} &&
    cp -r go/pkg ${output} &&
    cp -r go/src ${output} &&
    trac "export GOROOT=$output" &&
    info "install go to $output success." && return 0
    warn "install go to $output failed." && return 255
}

function install_python3() {
    output=$1
    mkdir -p source && cd source &&
    wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz &&
    tar -xzf Python-3.6.0.tgz &&
    cd Python-3.6.0 &&
    ./configure --prefix=${output} &&
    make -j8 && make install &&
    export PATH=${output}/bin:$PATH &&
    python3 -m pip install pymysql &&
    python3 -m pip install murmurhash3 &&
    python3 -m pip install httplib2 &&
    python3 -m pip install kafka &&
    python3 -m pip install kafka-python &&
    python3 -m pip install pymongo &&
    python3 -m pip install psycopg2 &&
    python3 -m pip install pyquery &&
    trac "export PATH=${output}/bin:\$PATH" &&
    info "install python3 $output success." && return 0
    warn "install python3 $output failed." && return 255
}

function install_zsh() {
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" &&
    sed -i 's/^ZSH_THEME=.*$/ZSH_THEME="gianu"/g' ~/.zshrc &&
    info "install zsh success." && return 0
    warn "install zsh failed." && return 255
}

function install_nodejs() {
    output=$1
    mkdir -p source && cd source &&
    wget https://nodejs.org/dist/v6.10.2/node-v6.10.2.tar.gz &&
    tar -xzvf node-v6.10.2.tar.gz &&
    cd node-v6.10.2 &&
    ./configure --prefix=${output} &&
    make -j8 && make install &&
    trac "export PATH=${output}/bin:\$PATH" &&
    info "install nodejs $output success." && return 0
    warn "install nodejs $output failed." && return 255
}

function install_protoc() {
    output=$1
    mkdir -p source && cd source &&
    wget https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz &&
    tar -xzvf protobuf-cpp-3.2.0.tar.gz &&
    cd protobuf-3.2.0 &&
    ./configure --prefix=${output} &&
    make -j8 && make install &&
    trac "export PATH=${output}/bin:\$PATH" &&
    info "install protoc success" && return 0
    warn "install protoc fail" && return 255
}

function usage() {
    info "usage: sh hinstall <module> [prefix=./output]"
    info "  module  模块名"
    info "  prefix  路径"
    info ""
    info "module列表"
    info "  redis [centos, macos]"
    info "  go [centos]"
    info "  zsh [centos, macos]"
    info "  python3 [centos, macos]"
    info "  nodejs [centos, macos]"
}

function main() {
    output=$(pwd)/output
    if [[ ! -z $2 ]]; then
        output=$2
    fi
    mkdir -p ${output}

    case $1 in
        "redis") install_redis ${output};;
        "go") install_go ${output};;
        "zsh") install_zsh;;
        "python3") install_python3 ${output};;
        "nodejs") install_nodejs ${output};;
        *) usage;;
    esac
}

main $@

